#!/usr/bin/env python3
"""Prepare this repo's content for RAG ingestion.

The ingester has no `.tex` handler -- it drops LaTeX SILENTLY, reporting a
successful ingest of zero files. Most of this repo is LaTeX, so the corpus has
to be staged first. This script does that, plus the two dedupe passes that keep
the same lecture from being returned three times.

    ./prepare_corpus.py --plan          show what would happen, write nothing
    ./prepare_corpus.py                 build the corpus
    ./prepare_corpus.py --only cec_315  one course
    ./prepare_corpus.py --force         reconvert even if up to date

Output goes to ./corpus/<course>/... mirroring content/<course>/....
It lives INSIDE the repo on purpose: the container gets exactly one read-only
bind (${DOCS_PATH}:${DOCS_PATH}:ro), so a staging tree outside the repo root
would be invisible to it.

THREE THINGS THIS FIXES, each verified rather than assumed:

  1. .tex -> .md via `pandoc -f latex+raw_tex`. The `+raw_tex` is REQUIRED:
     plain `-f latex` silently discards content inside custom macros, and in
     this repo custom macros are exactly where final answers live
     (\\finalanswer in stat_412, answerbox in cesc_410). Measured on
     stat_412/QZ04/solutions/q01.tex: plain latex kept 1 of 2 occurrences of
     the answer "180"; +raw_tex kept both.

  2. Duplicate PDFs. 73 byte-identical copies across 56 groups (32 MB) --
     cec_315/exam*/lectures/ mirrors all_lectures/, cec_300/exam1/ mirrors
     course_content/. Deduped by md5, first path wins.

  3. .tex/.pdf twins. 62 .tex files have a same-name compiled .pdf beside them.
     The .tex is authoritative and converts cleanly, so its .pdf twin is
     skipped to avoid indexing the same content twice.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONTENT = REPO / "content"
CORPUS = Path(__file__).resolve().parent / "corpus"

# Directories that must never be walked. The venv alone is 5,287 files / 280 MB
# and would dwarf the actual corpus.
EXCLUDE_DIRS = {
    ".venv", "venv", "env", "__pycache__", ".obsidian", ".worklogs", "tmp",
    "node_modules", ".git", "public", "resources", "_vendor", ".pytest_cache",
    ".ruff_cache", "figs", ".ipynb_checkpoints",
    # Self-contained Overleaf exports: the preamble is inlined but the body
    # prose is byte-for-byte the parent .tex, so converting both puts the same
    # passage in the index twice. The md5 dedupe pass cannot see it -- the
    # inlined preamble makes the files differ. config.yaml excludes "overleaf/"
    # as well, so the duplicates are dropped whether they reach corpus/ or not.
    "overleaf",
}

# Courses too small to warrant their own knowledge base; folded into `misc`.
# cesc_470 was promoted OUT of misc (it has its own KB); keeping it here only
# made the per-course report print a misleading "-> misc" tag.
MISC_COURSES = {"cs_420"}

PANDOC_ARGS = ["-f", "latex+raw_tex", "-t", "markdown", "--wrap=none"]


def walk(root: Path):
    """Yield files under root, skipping excluded directories entirely."""
    for p in root.rglob("*"):
        if p.is_file() and not (set(p.relative_to(root).parts[:-1]) & EXCLUDE_DIRS):
            yield p


def md5(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def convert_tex(src: Path, dst: Path) -> tuple[bool, str]:
    """pandoc .tex -> .md. Returns (ok, message)."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        r = subprocess.run(["pandoc", str(src), *PANDOC_ARGS, "-o", str(dst)],
                           capture_output=True, timeout=120)
    except subprocess.TimeoutExpired:
        return False, "pandoc timed out"
    if r.returncode != 0:
        return False, r.stderr.decode(errors="replace").strip().splitlines()[-1][:120]
    if not dst.exists() or dst.stat().st_size == 0:
        return False, "produced an empty file"
    # Prepend provenance so a retrieved chunk can be traced to its source.
    rel = src.relative_to(REPO)
    body = dst.read_text(encoding="utf-8", errors="replace")
    dst.write_text(f"# {src.stem}\n\n*Source: `{rel}`*\n\n{body}", encoding="utf-8")
    return True, ""


def course_of(path: Path) -> str:
    rel = path.relative_to(CONTENT)
    return rel.parts[0] if len(rel.parts) > 1 else "_root"


# Marker lines delimiting the generated block in config.yaml. Everything
# between them is rewritten on each run; everything outside is left alone.
GEN_BEGIN = "  # >>> generated by prepare_corpus.py -- do not edit by hand >>>"
GEN_END = "  # <<< generated by prepare_corpus.py <<<"


def _write_excludes(skip: set[Path]) -> None:
    """Patch the skip set into config.yaml's shared exclude anchor.

    Writing the list to a text file is NOT enough -- nothing reads it, so the
    duplicates get indexed anyway. That was the original bug: 135 files were
    listed as skipped and every one of them was still ingested.

    `_is_excluded` (app/ingestion.py:1046-1063) fnmatches each pattern against
    the path RELATIVE TO THE INGEST ROOT, so patterns are written relative to
    content/<course>. They can all live in the ONE shared anchor: each glob
    contains its own course-specific subpath (`hw/hw01/p06_convolution.pdf`),
    so it simply never matches under a different course's root.
    """
    # Leading '*' so ONE pattern covers both root shapes: a course KB whose
    # root is content/<course> (rel = "HW07/solutions/q01.pdf") and `primary`
    # whose root is content/ (rel = "stat_412/HW07/solutions/q01.pdf").
    # fnmatch's '*' crosses '/', and matches empty, so both hit. Without it the
    # duplicates stay in `primary` -- verified.
    globs = sorted("*" + "/".join(p.relative_to(CONTENT).parts[1:]) for p in skip)

    (CORPUS / "_skip_pdfs.txt").write_text(
        "# Advisory listing, repo-relative. The ENFORCED copy is the generated\n"
        "# block inside config.yaml's shared exclude anchor.\n"
        + "\n".join(sorted(str(p.relative_to(REPO)) for p in skip)) + "\n",
        encoding="utf-8")

    cfg = Path(__file__).resolve().parent / "config.yaml"
    if not cfg.exists():
        print(f"\n{len(globs)} exclude globs computed, but {cfg.name} not found")
        return

    block = [
        GEN_BEGIN,
        "    # PDFs superseded by a .tex twin (the .tex is converted into",
        "    # corpus/<course>/ and indexed from there), plus byte-identical",
        "    # duplicate PDFs. Paths are relative to each KB's ingest root.",
        *(f"    - {g!r}" for g in globs),
        GEN_END,
    ]

    lines = cfg.read_text(encoding="utf-8").split("\n")
    out, i, replaced = [], 0, False
    while i < len(lines):
        if lines[i].rstrip() == GEN_BEGIN.rstrip():
            while i < len(lines) and lines[i].rstrip() != GEN_END.rstrip():
                i += 1
            i += 1                       # skip the old end marker
            out.extend(block)
            replaced = True
            continue
        out.append(lines[i])
        i += 1

    if not replaced:
        # First run: append to the shared anchor, which ends at the blank line
        # before the next top-level key.
        try:
            start = next(n for n, l in enumerate(out) if l.startswith("  exclude: &ex"))
        except StopIteration:
            print("\n! could not find 'exclude: &ex' in config.yaml — not patched")
            return
        end = start + 1
        while end < len(out) and (out[end].startswith("    ") or not out[end].strip()):
            if not out[end].strip():
                break
            end += 1
        out[end:end] = block

    cfg.write_text("\n".join(out), encoding="utf-8")
    print(f"\npatched {len(globs)} exclude globs into {cfg.name} "
          f"({'updated' if replaced else 'inserted'})")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--plan", action="store_true", help="report only, write nothing")
    ap.add_argument("--only", metavar="COURSE", help="restrict to one course folder")
    ap.add_argument("--force", action="store_true", help="reconvert even if up to date")
    args = ap.parse_args()

    if not CONTENT.is_dir():
        print(f"error: {CONTENT} not found", file=sys.stderr)
        return 1
    if not args.plan:
        import shutil
        if not shutil.which("pandoc"):
            print("error: pandoc not found (apt install pandoc)", file=sys.stderr)
            return 1

    files = list(walk(CONTENT))
    if args.only:
        files = [f for f in files if course_of(f) == args.only]
        if not files:
            print(f"no files for course {args.only!r}")
            return 1

    tex = [f for f in files if f.suffix.lower() == ".tex"]
    pdf = [f for f in files if f.suffix.lower() == ".pdf"]
    md = [f for f in files if f.suffix.lower() == ".md"]

    # --- pass 1: .tex/.pdf twins -- the .tex wins ------------------------
    tex_stems = {(f.parent, f.stem) for f in tex}
    twin_pdfs = {f for f in pdf if (f.parent, f.stem) in tex_stems}

    # --- pass 2: byte-identical PDFs -- first path wins -------------------
    by_hash: dict[str, list[Path]] = defaultdict(list)
    for f in sorted(set(pdf) - twin_pdfs):
        by_hash[md5(f)].append(f)
    dup_pdfs = {p for group in by_hash.values() for p in group[1:]}

    print(f"content/: {len(files)} files  ({len(md)} md, {len(tex)} tex, {len(pdf)} pdf)")
    print(f"  .tex to convert          {len(tex)}")
    print(f"  .pdf skipped (tex twin)  {len(twin_pdfs)}")
    print(f"  .pdf skipped (duplicate) {len(dup_pdfs)}")
    print(f"  .pdf indexed in place    {len(pdf) - len(twin_pdfs) - len(dup_pdfs)}")
    print(f"  .md  indexed in place    {len(md)}")

    # Write the skip list where the ingest config can consume it, so the
    # dedupe decision is data rather than a comment in a YAML file.
    per_course: dict[str, int] = defaultdict(int)
    ok = fail = skipped = 0
    failures: list[str] = []

    if not args.plan:
        CORPUS.mkdir(parents=True, exist_ok=True)
        _write_excludes(twin_pdfs | dup_pdfs)

    for src in sorted(tex):
        course = course_of(src)
        dst = CORPUS / src.relative_to(CONTENT).with_suffix(".md")
        if args.plan:
            per_course[course] += 1
            continue
        if not args.force and dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            skipped += 1
            per_course[course] += 1
            continue
        good, msg = convert_tex(src, dst)
        if good:
            ok += 1
            per_course[course] += 1
        else:
            fail += 1
            failures.append(f"{src.relative_to(REPO)}: {msg}")

    print()
    if args.plan:
        print("per-course .tex that would be converted:")
    else:
        print(f"converted {ok}, up-to-date {skipped}, failed {fail}")
        print("\nper-course .md now in corpus/:")
    for c, n in sorted(per_course.items(), key=lambda kv: -kv[1]):
        tag = "  -> misc" if c in MISC_COURSES else ""
        print(f"  {c:<14} {n:>4}{tag}")

    if failures:
        print(f"\nfailures ({len(failures)}):")
        for f in failures[:20]:
            print(f"  ! {f}")
        if len(failures) > 20:
            print(f"  ... and {len(failures)-20} more")

    if not args.plan:
        print(f"\ncorpus at {CORPUS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
